### ISSUE TITLE
Есть админ бот и капча бот. Так вот там код повторяется, а я бы хотел вынести функционал кспчи в отдельный модуль

### ISSUE THREAD

**Issue by Piterden** [JS-Liberty/codewars-solutions#4]
https://github.com/Piterden/captcha_only_bot/commit/2fdd7302c705679ef0f5de7e635bafa3a077f6f5

**Comment by Piterden** [comment]
Короче, не получилось и пришлось дублировать код. Ну как минимум это работает.

**Comment by faergeek** [comment]
Хм, а почему это оказалось в репозе про каты?))
